# Generated by Django 5.0.4 on 2024-05-03 12:31

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=users.models.user_profile_image_path),
        ),
    ]
